apiVersion: v1
kind: Pod
metadata:
  name: pod-myapp
  namespace: default
  labels:
    label1: L1
spec:
  containers:
  - name: container-myapp
    image: linanster/myapp:v1
    imagePullPolicy: IfNotPresent
