apiVersion: v1
kind: Service
metadata:
  name: service-myapp-clusterip
  namespace: default
spec:
  selector:
    label1: L1
  type: ClusterIP
  clusterIP: 10.98.98.98
  ports:
  - port: 8080
    targetPort: 80
