apiVersion: v1
kind: Service
metadata:
  name: service-myapp-nodeport
  namespace: default
spec:
  selector:
    label1: L1
  type: NodePort
  clusterIP: 10.99.99.99
  ports:
  - port: 8080
    targetPort: 80
    nodePort: 30080
