apiVersion: v1
kind: Pod
metadata:
  name: pod-volume-emptypath
  namespace: default
spec:
  volumes:
  - name: volume-html
    emptyDir: {}
  containers:
  - name: container-nginx
    image: nginx:1.14-alpine
    volumeMounts:
    - name: volume-html
      mountPath: /usr/share/nginx/html/
  - name: container-busybox
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: volume-html
      mountPath: /tmp
    command: ["/bin/sh","-c","sleep 3600"]

